<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | EUNOIA Technologies</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
						background-color: #050508;
						color: #cbd5e1;
						margin: 0;
						padding: 40px;
						line-height: 1.6;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: rgba(15, 23, 42, 0.6);
						border: 1px solid rgba(0, 212, 255, 0.2);
						border-radius: 20px;
						padding: 40px;
						backdrop-filter: blur(10px);
						box-shadow: 0 20px 50px rgba(0,0,0,0.5);
					}
					h1 {
						color: #00d4ff;
						margin: 0 0 10px;
						font-weight: 700;
						letter-spacing: -1px;
						font-size: 2.5rem;
					}
					.stats {
						margin-bottom: 30px;
						padding: 20px;
						background: linear-gradient(90deg, rgba(0, 212, 255, 0.1), transparent);
						border-radius: 12px;
						border-left: 4px solid #00d4ff;
						font-size: 1rem;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						border-bottom: 2px solid rgba(0, 212, 255, 0.2);
						padding: 15px 12px;
						color: #8338ec;
						font-weight: 600;
						text-transform: uppercase;
						font-size: 0.75rem;
						letter-spacing: 2px;
					}
					td {
						padding: 15px 12px;
						border-bottom: 1px solid rgba(255, 255, 255, 0.05);
						font-size: 0.95rem;
					}
					tr:hover td {
						background: rgba(0, 212, 255, 0.03);
					}
					a {
						color: #00d4ff;
						text-decoration: none;
						transition: all 0.2s ease;
					}
					a:hover {
						color: #ff006e;
						text-decoration: underline;
					}
					.lastmod {
						color: #64748b;
						font-family: 'Menlo', 'Monaco', 'Courier New', monospace;
					}
					.priority-tag {
						padding: 4px 8px;
						border-radius: 6px;
						font-weight: bold;
						font-size: 0.8rem;
					}
					.p-high { background: rgba(34, 197, 94, 0.2); color: #22c55e; }
					.p-mid { background: rgba(245, 158, 11, 0.2); color: #f59e0b; }
					.footer {
						margin-top: 60px;
						text-align: center;
						font-size: 0.85rem;
						color: #475569;
						padding-top: 20px;
						border-top: 1px solid rgba(255, 255, 255, 0.05);
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>EUNOIA Sitemap</h1>
					<p>Engine-optimized index of EUNOIA Technologies digital ecosystem.</p>
					
					<div class="stats">
						Total indexed resources: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
					</div>

					<table>
						<thead>
							<tr>
								<th>LOCATION</th>
								<th>PRIORITY</th>
								<th>FREQ</th>
								<th>LAST MODIFIED</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<xsl:variable name="itemURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<a href="{$itemURL}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<span>
											<xsl:choose>
												<xsl:when test="sitemap:priority &gt; 0.9">
													<xsl:attribute name="class">priority-tag p-high</xsl:attribute>
												</xsl:when>
												<xsl:otherwise>
													<xsl:attribute name="class">priority-tag p-mid</xsl:attribute>
												</xsl:otherwise>
											</xsl:choose>
											<xsl:value-of select="sitemap:priority"/>
										</span>
									</td>
									<td>
										<xsl:value-of select="sitemap:changefreq"/>
									</td>
									<td class="lastmod">
										<xsl:value-of select="sitemap:lastmod"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>

					<div class="footer">
						Generated by EUNOIA AI Core &#169; 2026. Data valid as of <xsl:value-of select="sitemap:urlset/sitemap:url[1]/sitemap:lastmod"/>.
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
